"""Generate a questionnaire ``.py`` file from a questionnaire document.

The generated module is ordinary siamang code — the file a researcher would
have written by hand — and it defines the same two module-level names the
CLI and the platforms read: ``survey`` (a :class:`~siamang.core.Questionnaire`)
and, when the document carries compiler settings, quotas or a theme,
``options``. Running :func:`siamang.model.to_document` on the executed module
gives the original document back.

Generation is deterministic: one document and one generator version give
the same bytes. Sections, in order: docstring, imports, variables, questions,
pages, scripts, questionnaire, options. Every variable, question and page is
preceded by a ``# studio: …`` marker so a builder can map lines back to
document objects.
"""

from __future__ import annotations

import contextlib
import dataclasses
import keyword
import re
from typing import Any

from siamang.codegen import emit
from siamang.codegen.emit import BinOp, Call, Dict, List, Node, Raw, Tuple, Unary, literal, render
from siamang.codegen.format import FormatterUnavailable, format_source
from siamang.core.question import Question
from siamang.model.document import QUESTION_TYPES, SCHEMA_VERSION, DocumentError
from siamang.model.schema import validate_document

#: Written into ``document_versions.codegen_version`` by platforms.
CODEGEN_VERSION = "1.0"

_COMPARISONS = {
    "=": "eq",
    "!=": "ne",
    ">": "gt",
    ">=": "ge",
    "<": "lt",
    "<=": "le",
    "in": "isin",
    "not in": "notin",
}
_LOGICAL = {"and": ("&", "AND"), "or": ("|", "OR")}
_PAGE_FACTORIES = {
    "content": "ContentPage",
    "disqualification": "DisqualificationPage",
    "final": "FinalPage",
    "redirect": "RedirectPage",
}
#: Keyword parameters each page factory accepts (besides ``name``).
_FACTORY_PARAMS = {
    "content": {"body", "title", "show_if", "hide_if"},
    "disqualification": {"title", "body", "redirect_url", "redirect_delay", "show_if", "hide_if"},
    "final": {"title", "body", "redirect_url", "redirect_delay", "show_if"},
    "redirect": {"redirect_url", "title", "body", "redirect_delay", "show_if"},
}
_PAGE_KW_ORDER = (
    "title",
    "body",
    "redirect_url",
    "redirect_delay",
    "items",
    "next_if",
    "default_next",
    "randomize_blocks",
    "show_if",
    "hide_if",
)
_RESERVED = {
    "sg",
    "survey",
    "options",
    "scripts",
    "codebook",
    "datetime",
    "Quota",
    "UIConfig",
    "Option",
    "Media",
    "MissingValue",
    *_PAGE_FACTORIES.values(),
}
_IDENT_RE = re.compile(r"[^0-9a-zA-Z_]+")

DEFAULT_HEADER = (
    "Generated by `siamang codegen` from a questionnaire document (schema {schema}).\n"
    "It depends only on the siamang engine:\n"
    "\n"
    "    pip install siamang\n"
    "    siamang validate questionnaire.py\n"
    "    siamang preview  questionnaire.py\n"
    "\n"
    "The document is the source of truth; edit it and generate again."
)


def generate_questionnaire(
    document: dict[str, Any],
    *,
    header: str | None = None,
    format: bool = True,
) -> str:
    """Render ``document`` as Python source.

    ``header`` replaces the explanatory paragraph of the module docstring
    (``{schema}`` is substituted). With ``format=True`` the result is passed
    through ``ruff format``; when ruff is not installed the generator's own
    layout is returned unchanged.
    """

    validate_document(document)
    code = _Generator(document, header or DEFAULT_HEADER).render()
    if format:
        with contextlib.suppress(FormatterUnavailable):
            code = format_source(code)
    return code


class _Names:
    """Stable, collision-free module-level identifiers."""

    def __init__(self) -> None:
        self.taken: set[str] = set(_RESERVED)

    def claim(self, raw: str, *fallbacks: str) -> str:
        candidates = [raw, *fallbacks]
        for candidate in candidates:
            name = _identifier(candidate)
            if name not in self.taken:
                self.taken.add(name)
                return name
        base = _identifier(candidates[-1])
        index = 2
        while f"{base}_{index}" in self.taken:
            index += 1
        name = f"{base}_{index}"
        self.taken.add(name)
        return name


def _identifier(raw: str) -> str:
    name = _IDENT_RE.sub("_", raw).strip("_") or "x"
    if name[0].isdigit():
        name = f"v_{name}"
    if keyword.iskeyword(name) or name in {"None", "True", "False"}:
        name = f"{name}_var"
    return name


class _Generator:
    def __init__(self, document: dict[str, Any], header: str) -> None:
        self.doc = document
        self.header = header.format(schema=document.get("schema_version", SCHEMA_VERSION))
        self.names = _Names()
        self.variables: dict[str, str] = {}
        self.questions: dict[str, str] = {}
        self.pages: dict[str, str] = {}
        self.imports: set[str] = set()
        self.used_variables: set[str] = set()

    # ── driver ───────────────────────────────────────────────────────────

    def render(self) -> str:
        for name in self.doc.get("variables") or {}:
            self.variables[name] = self.names.claim(name, f"{name}_var")
        questions = list(_walk_questions(self.doc.get("pages") or []))
        for question in questions:
            qid = question["id"]
            if qid in self.questions:
                raise DocumentError(f"Duplicate question id {qid!r}.")
            self.questions[qid] = self.names.claim(qid, f"q_{qid}")
        for page in self.doc.get("pages") or []:
            self.pages[page["name"]] = self.names.claim(f"page_{page['name']}")

        sections: list[str] = []
        sections.append(self._variables_section())
        sections.append(self._questions_section(questions))
        sections.append(self._pages_section())
        scripts_section = self._scripts_section()
        if scripts_section:
            sections.append(scripts_section)
        sections.append(self._questionnaire_section())
        options_section = self._options_section()
        if options_section:
            sections.append(options_section)

        body = "\n\n".join(section for section in sections if section)
        return f"{self._docstring()}\n\n{self._imports()}\n\n{body}\n"

    # ── head ─────────────────────────────────────────────────────────────

    def _docstring(self) -> str:
        title = self.doc["title"].replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        return f'"""{title} — survey as code.\n\n{self.header}\n"""'

    def _imports(self) -> str:
        lines = []
        if "datetime" in self.imports:
            lines.append("from datetime import datetime")
            lines.append("")
        lines.append("import siamang as sg")
        top = sorted(
            name for name in self.imports if name in {"Media", "MissingValue", "Option", "Quota"}
        )
        if top:
            lines.append(f"from siamang import {', '.join(top)}")
        factories = sorted(name for name in self.imports if name in _PAGE_FACTORIES.values())
        if factories:
            lines.append(f"from siamang.core import {', '.join(factories)}")
        if "UIConfig" in self.imports:
            lines.append("from siamang.frontend import UIConfig")
        return "\n".join(lines)

    # ── variables ────────────────────────────────────────────────────────

    def _variables_section(self) -> str:
        variables = self.doc.get("variables") or {}
        if not variables:
            return ""
        chunks = [_banner("Variables (codebook)")]
        for name, payload in variables.items():
            chunks.append(
                f"# studio: var {name}\n{self.variables[name]} = {render(self._variable(name, payload))}"
            )
        return "\n\n".join(chunks)

    def _variable(self, name: str, payload: dict[str, Any]) -> Node:
        kwargs: list[tuple[str, Node]] = [("scale", literal(payload["scale"]))]
        if payload.get("label") is not None:
            kwargs.append(("label", literal(payload["label"])))
        labels = _codebook(payload.get("labels"))
        if labels:
            kwargs.append(
                ("labels", Dict(tuple((literal(code), literal(text)) for code, text in labels)))
            )
        missing = payload.get("missing") or []
        if missing:
            kwargs.extend(self._missing_kwargs(missing))
        elif payload.get("missing_values"):
            kwargs.append(("missing_values", literal(list(payload["missing_values"]))))
            missing_labels = _codebook(payload.get("missing_labels"))
            if missing_labels:
                kwargs.append(
                    (
                        "missing_labels",
                        Dict(
                            tuple((literal(code), literal(text)) for code, text in missing_labels)
                        ),
                    )
                )
        for key in ("dtype", "role", "description", "construct", "source"):
            if payload.get(key) is not None:
                kwargs.append((key, literal(payload[key])))
        if payload.get("valid_range") is not None:
            low, high = payload["valid_range"]
            kwargs.append(("valid_range", Tuple((literal(low), literal(high)))))
        return Call("sg.Variable", (literal(name),), tuple(kwargs))

    def _missing_kwargs(self, missing: list[dict[str, Any]]) -> list[tuple[str, Node]]:
        plain = all(item.get("kind", "system_missing") == "system_missing" for item in missing)
        if plain:
            kwargs: list[tuple[str, Node]] = [
                ("missing_values", List(tuple(literal(item["code"]) for item in missing)))
            ]
            labeled = [item for item in missing if item["label"] != str(item["code"])]
            if labeled:
                kwargs.append(
                    (
                        "missing_labels",
                        Dict(tuple((literal(i["code"]), literal(i["label"])) for i in labeled)),
                    )
                )
            return kwargs
        self.imports.add("MissingValue")
        items = []
        for item in missing:
            kw: tuple[tuple[str, Node], ...] = ()
            if item.get("kind", "system_missing") != "system_missing":
                kw = (("kind", literal(item["kind"])),)
            items.append(Call("MissingValue", (literal(item["code"]), literal(item["label"])), kw))
        return [("missing", Tuple(tuple(items)))]

    # ── questions ────────────────────────────────────────────────────────

    def _questions_section(self, questions: list[dict[str, Any]]) -> str:
        if not questions:
            return ""
        chunks = [_banner("Questions")]
        for question in questions:
            qid = question["id"]
            chunks.append(
                f"# studio: {qid}\n{self.questions[qid]} = {render(self._question(question))}"
            )
        return "\n\n".join(chunks)

    def _question(self, payload: dict[str, Any]) -> Node:
        cls = QUESTION_TYPES[payload["type"]]
        where = f"question '{payload['id']}'"
        defaults = _defaults(cls)
        args: list[Node] = [literal(payload["text"])]
        kwargs: list[tuple[str, Node]] = []

        var = payload["var"]
        if isinstance(var, list):
            refs = List(tuple(self._var_ref(name, where) for name in var))
            if payload["type"] == "MultiChoice":
                kwargs.append(("vars", refs))
            else:
                kwargs.append(("var", refs))
        else:
            kwargs.append(("var", self._var_ref(var, where)))

        for field in dataclasses.fields(cls):
            key = field.name
            if key in {"text", "var", "id"} or key not in payload:
                continue
            if key == "mode" and isinstance(var, list):
                continue  # implied by vars=
            value = payload[key]
            if key in defaults and value == defaults[key]:
                continue
            kwargs.append((key, self._question_field(key, value, where)))
        kwargs.append(("id", literal(payload["id"])))
        return Call(f"sg.{cls.__name__}", tuple(args), tuple(kwargs))

    def _question_field(self, key: str, value: Any, where: str) -> Node:
        if key in {"show_if", "hide_if"}:
            return self._condition(value, where)
        if key == "media":
            if isinstance(value, list):
                return List(tuple(self._media(item) for item in value))
            return self._media(value)
        if key == "choices":
            return List(tuple(self._option(item, where) for item in value))
        return literal(value)

    def _option(self, payload: dict[str, Any], where: str) -> Node:
        self.imports.add("Option")
        kwargs: list[tuple[str, Node]] = []
        for key in ("show_if", "hide_if"):
            if payload.get(key) is not None:
                kwargs.append(
                    (key, self._condition(payload[key], f"{where} option {payload['code']!r}"))
                )
        if payload.get("media") is not None:
            kwargs.append(("media", self._media(payload["media"])))
        return Call("Option", (literal(payload["code"]), literal(payload["label"])), tuple(kwargs))

    def _media(self, payload: dict[str, Any]) -> Node:
        self.imports.add("Media")
        kwargs: list[tuple[str, Node]] = []
        for key in ("kind", "alt", "caption"):
            if payload.get(key) is not None:
                kwargs.append((key, literal(payload[key])))
        if payload.get("autoplay"):
            kwargs.append(("autoplay", Raw("True")))
        if payload.get("loop"):
            kwargs.append(("loop", Raw("True")))
        if payload.get("controls") is False:
            kwargs.append(("controls", Raw("False")))
        return Call("Media", (literal(payload["url"]),), tuple(kwargs))

    def _var_ref(self, name: str, where: str) -> Node:
        if name not in self.variables:
            raise DocumentError(f"{where}: unknown variable '{name}'.")
        self.used_variables.add(name)
        return Raw(self.variables[name])

    # ── conditions ───────────────────────────────────────────────────────

    def _condition(self, payload: dict[str, Any], where: str) -> Node:
        kind = payload.get("type")
        if kind == "raw":
            return literal(payload["text"])
        if kind == "var":
            return self._varref_node(payload)
        if kind != "expression":
            raise DocumentError(f"{where}: unknown condition type {kind!r}.")
        return self._expression(payload, where, depth=True)

    def _expression(self, node: dict[str, Any], where: str, *, depth: bool) -> Node:
        """``depth`` is True at the top of a condition, where ``& | ~`` read well."""

        op = node["op"]
        left, right = node.get("left"), node.get("right")
        if op in _COMPARISONS and self._is_known_var(left):
            self.used_variables.add(left["name"])
            return Call(
                f"{self.variables[left['name']]}.{_COMPARISONS[op]}",
                (self._operand(right, where),),
            )
        if op == "not":
            inner = self._operand(left, where)
            if depth and self._is_simple(left):
                return Unary("~", inner)
            return Call("sg.NOT", (inner,))
        if op in _LOGICAL:
            parts = _flatten(node, op)
            symbol, function = _LOGICAL[op]
            if depth and len(parts) == 2 and all(self._is_simple(item) for item in parts):
                left_node, right_node = (
                    self._expression(item, where, depth=True) for item in parts
                )
                return BinOp(symbol, _paren(left_node), _paren(right_node))
            return Call(f"sg.{function}", tuple(self._operand(item, where) for item in parts))
        if op == "raw":
            return Call("sg.Expression.raw", (literal(left),))
        return Call(
            "sg.Expression",
            (literal(op), self._operand(left, where), self._operand(right, where)),
        )

    def _operand(self, node: Any, where: str) -> Node:
        if _is_varref(node):
            return self._varref_node(node)
        if _is_expression(node):
            return self._expression(node, where, depth=False)
        if isinstance(node, list):
            return List(tuple(self._operand(item, where) for item in node))
        return literal(node)

    def _varref_node(self, node: dict[str, Any]) -> Node:
        """A variable reference as a value: always ``sg.VarRef`` — a Variable is not one."""

        return Call("sg.VarRef", (literal(node["name"]),))

    def _is_known_var(self, node: Any) -> bool:
        return _is_varref(node) and node["name"] in self.variables

    def _is_simple(self, node: Any) -> bool:
        """A comparison on a known variable, or its negation — what reads well with & | ~."""

        if not _is_expression(node):
            return False
        if node["op"] in _COMPARISONS:
            return self._is_known_var(node.get("left"))
        return node["op"] == "not" and self._is_simple(node.get("left"))

    # ── pages ────────────────────────────────────────────────────────────

    def _pages_section(self) -> str:
        pages = self.doc.get("pages") or []
        if not pages:
            return ""
        chunks = [_banner("Pages")]
        for page in pages:
            chunks.append(
                f"# studio: page {page['name']}\n{self.pages[page['name']]} = {render(self._page(page))}"
            )
        return "\n\n".join(chunks)

    def _page(self, page: dict[str, Any]) -> Node:
        where = f"page '{page['name']}'"
        kind = page.get("kind")
        present = {key for key in _PAGE_KW_ORDER if page.get(key) not in (None, [], False)}
        factory = _PAGE_FACTORIES.get(kind) if kind else None
        if factory and present <= _FACTORY_PARAMS[kind]:
            self.imports.add(factory)
            kwargs = [
                (key, self._page_field(key, page[key], where))
                for key in _PAGE_KW_ORDER
                if key in present
            ]
            return Call(factory, (literal(page["name"]),), tuple(kwargs))
        kwargs = [("name", literal(page["name"]))]
        if kind:
            kwargs.append(("kind", literal(kind)))
        for key in _PAGE_KW_ORDER:
            if key in present or (key == "items" and not kind):
                kwargs.append((key, self._page_field(key, page.get(key) or [], where)))
        return Call("sg.Page", (), tuple(kwargs))

    def _page_field(self, key: str, value: Any, where: str) -> Node:
        if key == "items":
            return List(tuple(self._item(item, where) for item in value))
        if key in {"show_if", "hide_if"}:
            return self._condition(value, f"{where} {key}")
        if key == "next_if":
            rules = []
            for rule in value:
                condition = rule.get("condition")
                cond_node = (
                    self._condition(condition, f"{where} next_if")
                    if condition is not None
                    else Raw("None")
                )
                rules.append(Tuple((cond_node, literal(rule["target"]))))
            return List(tuple(rules))
        return literal(value)

    def _item(self, item: dict[str, Any], where: str) -> Node:
        if item.get("type") == "Block":
            kwargs: list[tuple[str, Node]] = []
            if item.get("title") is not None:
                kwargs.append(("title", literal(item["title"])))
            location = (
                f"block '{item.get('title')}' in {where}"
                if item.get("title")
                else f"block in {where}"
            )
            kwargs.append(
                (
                    "items",
                    List(tuple(self._item(child, location) for child in item.get("items") or [])),
                )
            )
            if item.get("randomize"):
                kwargs.append(("randomize", Raw("True")))
            for key in ("show_if", "hide_if"):
                if item.get(key) is not None:
                    kwargs.append((key, self._condition(item[key], f"{location} {key}")))
            return Call("sg.Block", (), tuple(kwargs))
        return Raw(self.questions[item["id"]])

    # ── scripts ──────────────────────────────────────────────────────────

    def _scripts_section(self) -> str:
        scripts = self.doc.get("scripts") or []
        if not scripts:
            return ""
        items = List(tuple(self._script(script) for script in scripts))
        return f"{_banner('Scripts')}\n\nscripts = {render(items, 10)}"

    def _script(self, payload: dict[str, Any]) -> Node:
        kind = payload["type"]
        if kind == "randomize_options":
            kwargs = (
                (("seed", literal(payload["seed"])),) if payload.get("seed") is not None else ()
            )
            return Call("sg.Script.randomize_options", (literal(payload["question"]),), kwargs)
        if kind == "randomize_pages":
            return Call("sg.Script.randomize_pages")
        if kind == "timed_question":
            return Call(
                "sg.Script.timed_question",
                (literal(payload["question"]),),
                (("seconds", literal(int(payload["seconds"]))),),
            )
        if kind == "validate_fields_match":
            kwargs = (("message", literal(payload["message"])),) if "message" in payload else ()
            return Call(
                "sg.Script.validate_fields_match",
                (literal(payload["field_a"]), literal(payload["field_b"])),
                kwargs,
            )
        kwargs_list: list[tuple[str, Node]] = []
        if payload.get("name") is not None:
            kwargs_list.append(("name", literal(payload["name"])))
        kwargs_list.append(("trigger", literal(payload.get("trigger", "onPageEnter"))))
        if payload.get("target") is not None:
            kwargs_list.append(("target", literal(payload["target"])))
        code = payload["code"]
        code_node = Raw(emit.triple_string(code)) if "\n" in code else literal(code)
        kwargs_list.append(("code", code_node))
        if payload.get("context"):
            kwargs_list.append(("context", literal(payload["context"])))
        if payload.get("sandbox") is False:
            kwargs_list.append(("sandbox", Raw("False")))
        return Call("sg.Script", (), tuple(kwargs_list))

    # ── questionnaire and options ────────────────────────────────────────

    def _questionnaire_section(self) -> str:
        kwargs: list[tuple[str, Node]] = [("title", literal(self.doc["title"]))]
        kwargs.append(
            ("pages", List(tuple(Raw(self.pages[p["name"]]) for p in self.doc.get("pages") or [])))
        )
        if self.doc.get("scripts"):
            kwargs.append(("scripts", Raw("scripts")))
        if self.doc.get("deadline") is not None:
            self.imports.add("datetime")
            kwargs.append(
                ("deadline", Call("datetime.fromisoformat", (literal(self.doc["deadline"]),)))
            )
        unused = [name for name in self.variables if name not in self.used_variables]
        lines = [_banner("Questionnaire")]
        if unused:
            registry = List(tuple(Raw(self.variables[name]) for name in self.variables))
            lines.append(
                "# The codebook registers every variable, including the ones no question asks yet.\n"
                "codebook = sg.VariableMap()\n"
                f"codebook.add_many({render(registry, 18)})"
            )
            kwargs.append(("variables", Raw("codebook")))
        lines.append(f"survey = {render(Call('sg.Questionnaire', (), tuple(kwargs)), 9)}")
        return "\n\n".join(lines)

    def _options_section(self) -> str:
        options = self.doc.get("options") or {}
        quotas = self.doc.get("quotas") or []
        ui = self.doc.get("ui") or {}
        if not options and not quotas and not ui:
            return ""
        items: list[tuple[Node, Node]] = [(literal(k), literal(v)) for k, v in options.items()]
        if quotas:
            self.imports.add("Quota")
            items.append(
                (
                    literal("quota"),
                    List(
                        tuple(
                            Call(
                                "Quota",
                                (
                                    literal(q["variable"]),
                                    literal(q["target_value"]),
                                    literal(q["limit"]),
                                ),
                            )
                            for q in quotas
                        )
                    ),
                )
            )
        if ui:
            self.imports.add("UIConfig")
            items.append(
                (literal("ui"), Call("UIConfig", (), tuple((k, literal(v)) for k, v in ui.items())))
            )
        comment = (
            "# Compiler settings, theme and fieldwork quotas: read on deploy and publish,\n"
            "# checked by `siamang validate`."
        )
        return f"{comment}\noptions = {render(Dict(tuple(items)), 10)}"


# ─── helpers ─────────────────────────────────────────────────────────────────


def _banner(title: str) -> str:
    return f"# ── {title} " + "─" * max(0, 76 - len(title))


def _walk_questions(pages: list[dict[str, Any]]):
    def walk(items):
        for item in items:
            if item.get("type") == "Block":
                yield from walk(item.get("items") or [])
            else:
                yield item

    for page in pages:
        yield from walk(page.get("items") or [])


def _codebook(value: Any) -> list[tuple[Any, str]]:
    if not value:
        return []
    if isinstance(value, dict):
        return [(_parse_code(code), label) for code, label in value.items()]
    return [(item["code"], item["label"]) for item in value]


def _parse_code(key: str) -> Any:
    if re.fullmatch(r"-?\d+", key):
        return int(key)
    try:
        return float(key)
    except ValueError:
        return key


def _defaults(cls: type[Question]) -> dict[str, Any]:
    defaults: dict[str, Any] = {}
    for field in dataclasses.fields(cls):
        if field.default is not dataclasses.MISSING:
            defaults[field.name] = field.default
        elif field.default_factory is not dataclasses.MISSING:
            defaults[field.name] = field.default_factory()
    return defaults


def _is_varref(node: Any) -> bool:
    return isinstance(node, dict) and node.get("type") == "var"


def _is_expression(node: Any) -> bool:
    return isinstance(node, dict) and node.get("type") == "expression"


def _flatten(node: dict[str, Any], op: str) -> list[Any]:
    """``AND(a, b, c)`` nests to the left; unfold that spine back into a list."""

    items: list[Any] = []
    current = node
    while _is_expression(current) and current["op"] == op:
        items.append(current.get("right"))
        current = current.get("left")
    items.append(current)
    items.reverse()
    return items


def _paren(node: Node) -> Node:
    if isinstance(node, BinOp):
        return dataclasses.replace(node, parens=True)
    return node
