"""Brand Awareness Study 2026 — survey as code.

Generated by `siamang codegen` from a questionnaire document (schema 1.0).
It depends only on the siamang engine:

    pip install siamang
    siamang validate questionnaire.py
    siamang preview  questionnaire.py

The document is the source of truth; edit it and generate again.
"""

import siamang as sg
from siamang import Quota
from siamang.core import DisqualificationPage, FinalPage
from siamang.frontend import UIConfig

# ── Variables (codebook) ────────────────────────────────────────────────────────

# studio: var age
age = sg.Variable("age", scale="ratio", label="Age", valid_range=(16, 99))

# studio: var region
region = sg.Variable(
    "region",
    scale="nominal",
    label="Region",
    labels={1: "Capital", 2: "North", 3: "South"},
)

# studio: var gender
gender = sg.Variable(
    "gender", scale="nominal", label="Gender", labels={1: "Male", 2: "Female", 3: "Other"}
)

# studio: var aware
aware = sg.Variable(
    "aware",
    scale="nominal",
    label="Brands heard of (unaided)",
    labels={1: "Acme", 2: "Globex", 3: "Initech", 99: "None of these"},
)

# studio: var trust_acme
trust_acme = sg.Variable(
    "trust_acme",
    scale="ordinal",
    label="Trust: Acme",
    labels={1: "No trust", 2: "Low", 3: "Medium", 4: "High", 5: "Full", 9: "Refused"},
    missing_values=[9],
    missing_labels={9: "Refused"},
)

# studio: var trust_globex
trust_globex = sg.Variable(
    "trust_globex",
    scale="ordinal",
    label="Trust: Globex",
    labels={1: "No trust", 2: "Low", 3: "Medium", 4: "High", 5: "Full", 9: "Refused"},
    missing_values=[9],
    missing_labels={9: "Refused"},
)

# studio: var satisfaction
satisfaction = sg.Variable(
    "satisfaction",
    scale="ordinal",
    label="Overall satisfaction",
    labels={
        1: "Very dissatisfied",
        2: "Dissatisfied",
        3: "Neutral",
        4: "Satisfied",
        5: "Very satisfied",
    },
)

# studio: var comment
comment = sg.Variable("comment", scale="nominal", label="Free comment")

# ── Questions ───────────────────────────────────────────────────────────────────

# studio: q_age
q_age = sg.NumericInput("How old are you?", var=age, required=True, unit="years", id="q_age")

# studio: q_region
q_region = sg.SingleChoice(
    "Where do you live?", var=region, required=True, display="buttons", id="q_region"
)

# studio: q_gender
q_gender = sg.SingleChoice("What is your gender?", var=gender, id="q_gender")

# studio: q_aware
q_aware = sg.MultiChoice(
    "Which of these brands have you heard of?",
    var=aware,
    randomize=True,
    exclusive=[99],
    id="q_aware",
)

# studio: m_trust
m_trust = sg.Matrix(
    "How much do you trust each brand?",
    var=[trust_acme, trust_globex],
    na_option=True,
    id="m_trust",
)

# studio: q_sat
q_sat = sg.LikertScale(
    "How satisfied are you with brands in this category overall?",
    var=satisfaction,
    required=True,
    left_label="Very dissatisfied",
    right_label="Very satisfied",
    id="q_sat",
)

# studio: q_comment
q_comment = sg.OpenText(
    "Anything else you would like to add?",
    var=comment,
    multiline=True,
    max_chars=500,
    placeholder="Optional comments…",
    id="q_comment",
)

# ── Pages ───────────────────────────────────────────────────────────────────────

# studio: page screener
page_screener = sg.Page(
    name="screener",
    title="About you",
    items=[q_age, q_region, q_gender],
    next_if=[(age.lt(18), "screen_out")],
)

# studio: page screen_out
page_screen_out = DisqualificationPage(
    "screen_out",
    title="Thank you",
    body="<p>This study is for respondents aged 18 and over.</p>",
)

# studio: page awareness
page_awareness = sg.Page(
    name="awareness",
    title="Brands",
    items=[q_aware, sg.Block(title="Trust", items=[m_trust], show_if=~aware.isin([99]))],
)

# studio: page attitudes
page_attitudes = sg.Page(
    name="attitudes",
    title="Your experience",
    items=[q_sat, q_comment],
    show_if=sg.AND(age.ge(18), sg.OR(region.eq(1), region.eq(2))),
)

# studio: page thanks
page_thanks = FinalPage(
    "thanks", title="Thank you!", body="<p>Your answers have been recorded.</p>"
)

# ── Scripts ─────────────────────────────────────────────────────────────────────

scripts = [sg.Script.timed_question("q_aware", seconds=45)]

# ── Questionnaire ───────────────────────────────────────────────────────────────

survey = sg.Questionnaire(
    title="Brand Awareness Study 2026",
    pages=[page_screener, page_screen_out, page_awareness, page_attitudes, page_thanks],
    scripts=scripts,
)

# Compiler settings, theme and fieldwork quotas: read on deploy and publish,
# checked by `siamang validate`.
options = {
    "description": "Awareness and trust across regions, wave 2026-Q3.",
    "completion_text": "Thank you — your answers make the results better!",
    "metadata": {"wave": "2026-Q3", "estimated_minutes": 6},
    "quota": [Quota("region", 1, 400), Quota("region", 2, 400), Quota("region", 3, 400)],
    "ui": UIConfig(
        primary_color="#a8324b",
        font_pair="mixed",
        institution_name="Independent Polling Lab",
        estimated_minutes=6,
        progress_style="dots",
        default_theme="system",
    ),
}
