"""Satisfaction by region (flow: satisfaction_by_region).

Dedup, drop speeders, rake to region × gender, crosstab and group means, Markdown report.

Generated by `siamang codegen` from a flow document (schema 1.0). Run it
on the platform that holds the responses, or locally from a data snapshot:

    python scripts/satisfaction_by_region.py --data data/responses.parquet

The flow document is the source of truth; edit it and generate again.
"""

import argparse
import os
from pathlib import Path

from siamang.data import respondents, weights
from siamang.flow import live
from siamang.reporting import Report

from survey.questionnaire import survey

# ── Data source ─────────────────────────────────────────────────────────────────

parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
parser.add_argument(
    "--data", help="Local snapshot (Parquet/CSV/SAV) instead of the project database"
)
args = parser.parse_args()

# ── Responses: responses · main ─────────────────────────────────────────────────
# studio: src
if args.data:  # research bundle: reproduce from a data snapshot
    from siamang.io import read_snapshot

    n_src = read_snapshot(args.data, questionnaire=survey)
else:  # the platform: project database, scoped to this project
    from siamang_studio import db

    n_src = db.as_survey_data(
        "responses", environment="main", only_completed=False, questionnaire=survey
    )

# ── Dedup respondents: by respondent_id, keep last ──────────────────────────────
# studio: dedup
n_dedup = n_src.with_frame(
    respondents.dedup_responses(
        n_src.frame, id_col="respondent_id", order_by="submitted_at", keep="last"
    )
)

# ── Speeders & partials: ≥ 90 s ─────────────────────────────────────────────────
# studio: speed
_frame = n_dedup.frame.copy()
_frame["duration_s"] = respondents.completion_time(_frame)
_frame["partial"] = respondents.partial_flag(_frame, required=["age", "region", "satisfaction"])
_keep = ~respondents.speeders(_frame, min_seconds=90)
_keep &= ~_frame["partial"]
n_speed = n_dedup.with_frame(_frame[_keep])

# ── Rake weights ────────────────────────────────────────────────────────────────
# studio: rake
_frame = n_speed.frame.copy()
_frame["weight"] = weights.rake_weights(
    _frame,
    {"region": {1: 0.45, 2: 0.3, 3: 0.25}, "gender": {1: 0.48, 2: 0.5, 3: 0.02}},
    max_iter=50,
    tol=1e-06,
    cap=None,
)
n_rake = n_speed.with_frame(_frame)

# ── Live tile: Clean respondents ────────────────────────────────────────────────
# studio: tile_n
live.publish("tile_n", kind="number", label="Clean respondents", value=n_speed, metric="rows")

# ── Apply weight: weight ────────────────────────────────────────────────────────
# studio: apply
n_apply = n_rake.with_weight("weight")

# ── Crosstab: satisfaction × region ─────────────────────────────────────────────
# studio: xtab
n_xtab_table = n_apply.report.crosstab("satisfaction", "region", pct="col", test=True)
n_xtab_stat = n_xtab_table.stats

# ── Bar chart: satisfaction ─────────────────────────────────────────────────────
# studio: bar
n_bar = n_apply.plot.bar(
    "satisfaction",
    by="region",
    horizontal=False,
    show_values=True,
    title=None,
    figsize=(10.0, 6.0),
    palette="muted",
)

# ── Group means: satisfaction by region ─────────────────────────────────────────
# studio: means
n_means_table = n_apply.report.means("satisfaction", by="region", test=True)
n_means_stat = n_means_table.stats

# ── Report section: Overall satisfaction by region ──────────────────────────────
# studio: section
n_section = Report()
n_section.heading("Overall satisfaction by region")
n_section.text(
    "Column percentages, weighted by region × gender (raking). N after cleaning is reported below."
)
for _item, _caption, _layout in zip(
    [n_xtab_table, n_bar, n_means_table],
    [
        "Table 1. Satisfaction × region (%)",
        "Figure 1. Distribution by region",
        "Table 2. Mean satisfaction by region",
    ],
    [{}, {}, {}],
    strict=True,
):
    n_section.add(_item, caption=_caption, **_layout)

# ── Live tile: Satisfaction × region ────────────────────────────────────────────
# studio: tile_x
live.publish(
    "tile_x", kind="table", label="Satisfaction × region", value=n_xtab_table, metric="value"
)

# ── Save report: outputs/satisfaction_by_region.md ──────────────────────────────
# studio: save
n_save = Report.combine([n_section], title="Satisfaction 2026-Q3", toc=False, theme=None)
n_save.provenance(os.environ.get("SIAMANG_PROVENANCE"))
n_save.save("outputs/satisfaction_by_region.md")
n_save.save(Path("outputs/satisfaction_by_region.md").with_suffix(".html"))
