"""Generate the analysis script of a flow.

The script is what a researcher would have written by hand and what a
platform runs in batch: it loads the data, executes every node in order and
saves the outputs. Run it on a platform (the project database) or from a
research bundle::

    python scripts/satisfaction_by_region.py --data data/responses.parquet

Each node contributes exactly the text :mod:`siamang.flow.template` renders,
so the script and :class:`~siamang.flow.runner.FlowRunner` produce the same
results.
"""

from __future__ import annotations

import contextlib
from typing import Any

from siamang.codegen.format import FormatterUnavailable, format_source
from siamang.flow.document import FlowGraph, resolve_flow
from siamang.flow.registry import Registry
from siamang.flow.template import output_names, render_node, subtitle

FLOW_CODEGEN_VERSION = "1.0"

DEFAULT_HEADER = (
    "Generated by `siamang codegen` from a flow document (schema {schema}). Run it\n"
    "on the platform that holds the responses, or locally from a data snapshot:\n"
    "\n"
    "    python {script} --data data/responses.parquet\n"
    "\n"
    "The flow document is the source of truth; edit it and generate again."
)


def generate_flow(
    document: dict[str, Any],
    questionnaire: dict[str, Any] | None = None,
    *,
    registry: Registry | None = None,
    header: str | None = None,
    questionnaire_module: str = "survey.questionnaire",
    platform_module: str = "siamang_studio",
    format: bool = True,
) -> str:
    """Render the flow as a Python script.

    ``questionnaire`` is the questionnaire document; when given, variable
    parameters are checked against its codebook. ``questionnaire_module`` is
    where the script imports ``survey`` from; ``platform_module`` is the SDK
    that provides ``db`` on the platform.
    """

    graph = resolve_flow(document, registry=registry, questionnaire=questionnaire)
    code = _Generator(
        graph, header or DEFAULT_HEADER, questionnaire_module, platform_module
    ).render()
    if format:
        with contextlib.suppress(FormatterUnavailable):
            code = format_source(code, filename=f"{graph.name}.py")
    return code


class _Generator:
    def __init__(
        self, graph: FlowGraph, header: str, questionnaire_module: str, platform_module: str
    ) -> None:
        self.graph = graph
        self.header = header
        self.questionnaire_module = questionnaire_module
        self.platform_module = platform_module

    def render(self) -> str:
        graph = self.graph
        snapshot_nodes = [n for n in graph.order if graph.specs[n].snapshot]
        platform_nodes = [
            n for n in graph.order if graph.specs[n].platform and not graph.specs[n].snapshot
        ]
        uses_survey = any(
            graph.specs[n].snapshot or "survey" in _template_text(graph.specs[n])
            for n in graph.order
        )
        imports = {"import argparse"} if snapshot_nodes or platform_nodes else set()
        for node_id in graph.order:
            spec = graph.specs[node_id]
            if not spec.platform:
                imports.update(spec.imports)

        sections: list[str] = [self._docstring(), self._imports(imports, uses_survey)]
        if snapshot_nodes or platform_nodes:
            sections.append(self._arguments(snapshot_nodes))
        for node_id in graph.order:
            sections.append(self._node(node_id, snapshot_nodes))
        return "\n\n".join(section for section in sections if section) + "\n"

    def _docstring(self) -> str:
        doc = self.graph.document
        title = doc.get("title") or doc["name"]
        lines = [f"{title} (flow: {doc['name']})."]
        if doc.get("description"):
            lines += ["", doc["description"]]
        header = self.header.format(
            schema=doc.get("schema_version", "1.0"), script=f"scripts/{doc['name']}.py"
        )
        lines += ["", header]
        text = "\n".join(lines).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        return f'"""{text}\n"""'

    def _imports(self, statements: set[str], uses_survey: bool) -> str:
        stdlib = {s for s in statements if _module_of(s).split(".")[0] in _STDLIB}
        engine = statements - stdlib
        blocks = []
        if stdlib:
            blocks.append("\n".join(_sorted_imports(stdlib)))
        if engine:
            blocks.append("\n".join(_sorted_imports(engine)))
        if uses_survey:  # the project's own module: a first-party block of its own
            blocks.append(f"from {self.questionnaire_module} import survey")
        return "\n\n".join(blocks)

    def _arguments(self, snapshot_nodes: list[str]) -> str:
        lines = [
            _banner("Data source"),
            "",
            "parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])",
        ]
        if len(snapshot_nodes) <= 1:
            lines.append(
                'parser.add_argument("--data", help="Local snapshot (Parquet/CSV/SAV) instead of the project database")'
            )
        else:
            for node_id in snapshot_nodes:
                lines.append(
                    f'parser.add_argument("--data-{node_id.replace("_", "-")}", dest={node_id + "_data"!r}, '
                    f'help="Local snapshot for {node_id} instead of the project database")'
                )
        lines.append("args = parser.parse_args()")
        return "\n".join(lines)

    def _node(self, node_id: str, snapshot_nodes: list[str]) -> str:
        graph = self.graph
        spec = graph.specs[node_id]
        params = graph.params(node_id)
        sub = subtitle(spec, params)
        title = f"{spec.title}: {sub}" if sub else spec.title
        body = render_node(graph, node_id).rstrip("\n")
        lines = [_banner(title), f"# studio: {node_id}"]
        if spec.snapshot:
            arg = "args.data" if len(snapshot_nodes) <= 1 else f"args.{node_id}_data"
            name = output_names(node_id, spec)["data"]
            lines += [
                f"if {arg}:  # research bundle: reproduce from a data snapshot",
                "    from siamang.io import read_snapshot",
                "",
                f"    {name} = read_snapshot({arg}, questionnaire=survey)",
                "else:  # the platform: project database, scoped to this project",
            ]
            lines += [
                f"    {statement}" for statement in _platform_imports(spec, self.platform_module)
            ]
            lines.append("")
            lines += [f"    {line}" if line else "" for line in body.splitlines()]
        elif spec.platform:
            lines += [
                "if not args.data:  # platform only: the project database",
            ]
            lines += [
                f"    {statement}" for statement in _platform_imports(spec, self.platform_module)
            ]
            lines.append("")
            lines += [f"    {line}" if line else "" for line in body.splitlines()]
        else:
            lines.append(body)
        return "\n".join(lines)


_STDLIB = {"argparse", "json", "os", "pathlib", "sys"}


def _module_of(statement: str) -> str:
    return statement.split()[1]


def _sorted_imports(statements: set[str]) -> list[str]:
    """isort order: ``import x`` lines first, then ``from x import a, b`` merged per module."""

    plain = sorted(s for s in statements if s.startswith("import "))
    names: dict[str, set[str]] = {}
    for statement in statements:
        if statement.startswith("from "):
            module, imported = statement[5:].split(" import ", 1)
            names.setdefault(module, set()).update(n.strip() for n in imported.split(","))
    merged = [
        f"from {module} import {', '.join(sorted(names[module]))}" for module in sorted(names)
    ]
    return plain + merged


def _platform_imports(spec, platform_module: str) -> list[str]:
    return [statement.replace("siamang_studio", platform_module) for statement in spec.imports]


def _template_text(spec) -> str:
    return "\n".join(fragment.code for fragment in spec.template)


def _banner(title: str) -> str:
    return f"# ── {title} " + "─" * max(0, 76 - len(title))


__all__ = ["DEFAULT_HEADER", "FLOW_CODEGEN_VERSION", "generate_flow"]
