"""Choice data written out for whatever will estimate it next.

Hierarchical Bayes is where individual-level utilities come from, and it lives
in R — ``ChoiceModelR``, ``bayesm``, ``RSGHB`` — where the method has been
checked by the people who use it. Running a cut-down version of it here, on a
server with a two-minute budget, would be a worse answer wearing the same name.

So the answer to "we want HB" is this: the choices in the shape those packages
read, a dictionary saying what each column is, and a script that runs. What
comes back is the researcher's own estimate, on their machine, with as many
draws as they think it needs.

The format is ChoiceModelR's, which is ``bayesm``'s underneath: one row per
alternative, ``id`` / ``ques`` / ``alt``, then one column per item, then ``y``
carrying the number of the chosen alternative on the first row of each task and
zero on the rest. Every task has the same number of alternatives, because those
packages require it — which is why the export writes the paired coding of
best–worst rather than the sequential one this engine estimates on, and says so
here rather than letting someone discover it from a discrepancy.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from siamang.core.question import Conjoint, MaxDiff
    from siamang.data.survey_data import SurveyData

__all__ = ["write_conjoint_choices", "write_maxdiff_choices"]


def write_maxdiff_choices(
    data: SurveyData,
    question: MaxDiff | str,
    path: str | Path,
    *,
    weight: str | None = None,
) -> Path:
    """Write ``<stem>.csv``, ``<stem>.dictionary.json`` and ``<stem>.hb.R``.

    Returns the path of the CSV; the other two sit beside it.
    """

    import pandas as pd

    from siamang.data import maxdiff

    question = maxdiff.question_of(data, question)
    sets = maxdiff.choice_sets(data, question, weight=weight, coding="paired")
    read = maxdiff.answers(data, question)

    target = Path(path)
    if target.suffix.lower() != ".csv":
        target = target.with_suffix(".csv")
    target.parent.mkdir(parents=True, exist_ok=True)

    # The reference item is a column too. Dropping it would make the file a
    # different model from the one the dictionary describes, and a reader
    # cannot see an absence.
    terms = [*sets.names, sets.reference]
    columns = {f"x{i + 1}": sets.design[:, i] for i in range(len(sets.names))}

    respondents = list(read.frame["respondent"])
    sizes, starts = sets.sizes, sets.starts
    chosen_at = {}
    for set_index, start in enumerate(starts):
        block = sets.chosen[start : start + sizes[set_index]]
        chosen_at[set_index] = int(np.argmax(block)) + 1

    ids, ques, alt, y = [], [], [], []
    # Two sets per task in the paired coding, so set 2k and 2k+1 belong to the
    # same respondent and the same task.
    for set_index in range(len(starts)):
        respondent = respondents[set_index // 2]
        for position in range(sizes[set_index]):
            ids.append(respondent)
            ques.append(set_index + 1)
            alt.append(position + 1)
            y.append(chosen_at[set_index] if position == 0 else 0)

    frame = pd.DataFrame({"id": ids, "ques": ques, "alt": alt, **columns, "y": y})
    frame.to_csv(target, index=False)

    dictionary = {
        "question": question.text,
        "format": "ChoiceModelR / bayesm long format",
        "coding": "paired best-worst: each task appears twice, the second time negated",
        "rows": "one per alternative on offer",
        "reference": sets.reference,
        "columns": {
            "id": "respondent",
            "ques": "choice task, numbered across the whole file",
            "alt": "alternative within the task",
            "y": "number of the chosen alternative, on the first row of each task",
            **{
                f"x{i + 1}": f"1 when this alternative is {name} (negated on a worst task)"
                for i, name in enumerate(sets.names)
            },
        },
        "items": terms,
        "note": (
            f"{sets.reference!r} has no column: its utility is fixed at zero and every other "
            "utility is read against it."
        ),
    }
    target.with_name(f"{target.stem}.dictionary.json").write_text(
        json.dumps(dictionary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    target.with_name(f"{target.stem}.hb.R").write_text(
        _render_hb_script(target.name, len(sets.names)), encoding="utf-8"
    )
    return target


def _render_hb_script(csv_name: str, n_parameters: int) -> str:
    return f"""# Hierarchical Bayes for a MaxDiff, generated by siamang.
#
# Run from this script's directory:
#     Rscript {Path(csv_name).stem}.hb.R
#
# This script was generated and reviewed, but not executed, by the tool that
# wrote it — there is no R where the export runs. Read it before you trust it.
#
# The data is in ChoiceModelR's long format, which is bayesm's underneath:
#   id    respondent
#   ques  choice task, numbered across the whole file
#   alt   alternative within the task
#   x1..x{n_parameters}  one column per item; 1 for the item this alternative is,
#         negated on a "worst" task. The reference item has no column: its
#         utility is fixed at zero and the rest are read against it.
#   y     the chosen alternative's number, on the first row of each task
#
# Other tools read the same file with almost no work:
#   bayesm    ChoiceModelR calls rhierMnlRwMixture for you; use it directly if
#             you want control over the priors.
#   mlogit    dfidx(data, idx = c("ques", "alt"), choice = ...) after expanding
#             y down each task.
#   xlogit    Python: MixedLogit().fit(X=..., y=..., varnames=..., ids=ques,
#             alts=alt, panels=id)

if (!requireNamespace("ChoiceModelR", quietly = TRUE)) {{
  stop("install.packages('ChoiceModelR') first")
}}

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
script_file <- if (length(file_arg) > 0) sub("^--file=", "", file_arg[[1]]) else "."
base_dir <- dirname(normalizePath(script_file, mustWork = FALSE))
choices <- read.csv(file.path(base_dir, "{csv_name}"), stringsAsFactors = FALSE)

# Draws and burn-in are the two numbers worth changing. These are a starting
# point, not a recommendation: watch the trace the package prints and raise
# them until the chain has settled.
draws <- 20000
burn_in <- 10000

set.seed(20260913)  # stated, so the same file gives the same estimates twice
out <- ChoiceModelR::choicemodelr(
  data = choices,
  xcoding = rep(1, {n_parameters}),        # every column is already numeric
  mcmc = list(R = draws, use = draws - burn_in),
  options = list(save = TRUE, keep = 10)
)

# One row per respondent: their own utilities, on the same scale as the
# aggregate ones, with the reference item at zero.
utilities <- as.data.frame(out$betadraw[, , dim(out$betadraw)[3]])
names(utilities) <- paste0("x", seq_len({n_parameters}))
utilities$id <- unique(choices$id)
write.csv(utilities, file.path(base_dir, "hb_utilities.csv"), row.names = FALSE)
cat("wrote hb_utilities.csv —", nrow(utilities), "respondents\\n")
"""


def write_conjoint_choices(
    data: SurveyData,
    question: Conjoint | str,
    path: str | Path,
    *,
    weight: str | None = None,
) -> Path:
    """The same three files for a conjoint: CSV, column dictionary, HB script.

    A conjoint needs no re-coding to get there — its tasks already are choice
    sets with a constant number of alternatives, which is what the R packages
    want. The only thing worth saying in the dictionary is which level each
    column stands for, because ``x7`` is not self-explanatory at the other end.
    """

    import pandas as pd

    from siamang.data import conjoint

    question = conjoint.question_of(data, question)
    sets = conjoint.choice_sets(data, question, weight=weight)
    read = conjoint.answers(data, question)

    target = Path(path)
    if target.suffix.lower() != ".csv":
        target = target.with_suffix(".csv")
    target.parent.mkdir(parents=True, exist_ok=True)

    respondents = list(read.frame["respondent"])
    sizes, starts = sets.sizes, sets.starts
    columns = {f"x{i + 1}": sets.design[:, i] for i in range(sets.design.shape[1])}

    ids, ques, alt, y = [], [], [], []
    for set_index, start in enumerate(starts):
        block = sets.chosen[start : start + sizes[set_index]]
        picked = int(np.argmax(block)) + 1
        for position in range(sizes[set_index]):
            ids.append(respondents[set_index])
            ques.append(set_index + 1)
            alt.append(position + 1)
            y.append(picked if position == 0 else 0)

    frame = pd.DataFrame({"id": ids, "ques": ques, "alt": alt, **columns, "y": y})
    frame.to_csv(target, index=False)

    dictionary = {
        "question": question.text,
        "format": "ChoiceModelR / bayesm long format",
        "coding": "dummy, the first level of each attribute held at zero",
        "rows": "one per alternative on offer",
        "reference": sets.reference,
        "columns": {
            "id": "respondent",
            "ques": "choice task, numbered across the whole file",
            "alt": "alternative within the task",
            "y": "number of the chosen alternative, on the first row of each task",
            **{f"x{i + 1}": name for i, name in enumerate(sets.names)},
        },
        "attributes": [
            {
                "name": attribute.name,
                "label": attribute.label or attribute.name,
                "levels": [level.label for level in attribute.levels],
                "reference": attribute.levels[0].label,
            }
            for attribute in question.attributes
        ],
        "note": (
            "Every attribute's first level has no column: it is the reference, and the other "
            "levels of that attribute are read against it."
        ),
    }
    target.with_name(f"{target.stem}.dictionary.json").write_text(
        json.dumps(dictionary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    target.with_name(f"{target.stem}.hb.R").write_text(
        _render_hb_script(target.name, sets.design.shape[1]), encoding="utf-8"
    )
    return target
