"""R import bundle writer for SurveyData."""

from __future__ import annotations

from pathlib import Path

from siamang.core.variable import VariableMap
from siamang.data.survey_data import SurveyData
from siamang.io.csv import CSVWriter
from siamang.io.dictionary import DictionaryWriter


class RScriptWriter:
    """Write CSV + JSON dictionary + an R import script for a SurveyData object."""

    def write(self, data: SurveyData, path: str | Path) -> Path:
        script_path = _script_path(path)
        script_path.parent.mkdir(parents=True, exist_ok=True)
        csv_path = script_path.with_suffix(".csv")
        dictionary_path = script_path.with_name(f"{script_path.stem}_dictionary.json")

        CSVWriter().write(data, csv_path)
        DictionaryWriter().write(data.variables or VariableMap(), dictionary_path)
        script_path.write_text(
            _render_r_script(csv_path.name, dictionary_path.name),
            encoding="utf-8",
        )
        return script_path


def _script_path(path: str | Path) -> Path:
    output = Path(path)
    if output.suffix.lower() == ".r":
        return output
    return output / "import_survey.R"


def _render_r_script(csv_name: str, dictionary_name: str) -> str:
    return f'''# Generated by siamang. Run from this script's directory.
if (!requireNamespace("jsonlite", quietly = TRUE)) {{
  stop("Package 'jsonlite' is required to read the siamang dictionary JSON.")
}}

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
script_file <- if (length(file_arg) > 0) sub("^--file=", "", file_arg[[1]]) else "{csv_name}"
base_dir <- dirname(normalizePath(script_file, mustWork = FALSE))

data_path <- file.path(base_dir, "{csv_name}")
dictionary_path <- file.path(base_dir, "{dictionary_name}")

survey_data <- read.csv(data_path, stringsAsFactors = FALSE, check.names = FALSE)
survey_dictionary <- jsonlite::fromJSON(dictionary_path, simplifyVector = FALSE)

for (name in names(survey_dictionary)) {{
  variable <- survey_dictionary[[name]]
  if (!name %in% names(survey_data)) {{
    next
  }}

  if (!is.null(variable$missing) && length(variable$missing) > 0) {{
    missing_codes <- type.convert(
      unlist(lapply(variable$missing, function(item) item$code), use.names = FALSE),
      as.is = TRUE
    )
    survey_data[[name]][survey_data[[name]] %in% missing_codes] <- NA
  }}

  if (!is.null(variable$labels) && length(variable$labels) > 0) {{
    levels <- type.convert(names(variable$labels), as.is = TRUE)
    labels <- unname(unlist(variable$labels, use.names = FALSE))
    survey_data[[name]] <- factor(survey_data[[name]], levels = levels, labels = labels)
  }}
}}

survey_data
'''
