"""R import bundle writer for SurveyData.

Three files that belong together: the responses as ``<stem>.csv``, the codebook
as ``<stem>.dictionary.json`` (the name a snapshot's dictionary has, so
:func:`siamang.io.read_snapshot` finds it beside the CSV too), and
``<stem>.R``, which reads both and gives R what the codebook knows — missing
codes as ``NA``, labeled codes as factors, the variable's codebook label as
each column's ``label`` attribute. Nothing in it needs more than ``jsonlite``.
"""

from __future__ import annotations

from pathlib import Path

from siamang.core.variable import VariableMap
from siamang.data import multi
from siamang.data.survey_data import SurveyData
from siamang.io.csv import CSVWriter
from siamang.io.dictionary import DictionaryWriter


class RScriptWriter:
    """Write CSV + JSON dictionary + an R import script for a SurveyData object."""

    def write(self, data: SurveyData, path: str | Path) -> Path:
        script_path = _script_path(path)
        script_path.parent.mkdir(parents=True, exist_ok=True)
        csv_path = script_path.with_suffix(".csv")
        dictionary_path = script_path.with_name(f"{script_path.stem}.dictionary.json")

        CSVWriter().write(data, csv_path)
        DictionaryWriter().write(data.variables or VariableMap(), dictionary_path)
        # Multiple-choice answers reach the CSV as codes joined by ";" — one
        # cell, several codes — which a factor cannot hold: it would turn every
        # respondent who chose two options into NA.
        multiple = [name for name in data.frame.columns if multi.is_multi(data.frame[name])]
        script_path.write_text(
            _render_r_script(csv_path.name, dictionary_path.name, multiple),
            encoding="utf-8",
        )
        return script_path


def _script_path(path: str | Path) -> Path:
    output = Path(path)
    if output.suffix.lower() == ".r":
        return output
    return output / "import_survey.R"


def _r_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render_r_script(csv_name: str, dictionary_name: str, multiple: list[str]) -> str:
    listed = ", ".join(_r_string(name) for name in multiple)
    return f"""# Generated by siamang. Reads {csv_name} with its codebook, {dictionary_name}:
# the codebook's missing codes become NA, labeled codes become factors and each
# column's "label" attribute is its variable label from the codebook. Run it with
#   Rscript {Path(csv_name).stem}.R
# or source("path/to/{Path(csv_name).stem}.R") from R: the files are looked for
# beside this script, wherever it is run from.
if (!requireNamespace("jsonlite", quietly = TRUE)) {{
  stop("Package 'jsonlite' is required to read the siamang dictionary JSON.")
}}

script_file <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
if (is.null(script_file)) {{
  file_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  script_file <- if (length(file_arg) > 0) sub("^--file=", "", file_arg[[1]]) else "{csv_name}"
}}
base_dir <- dirname(normalizePath(script_file, mustWork = FALSE))

data_path <- file.path(base_dir, "{csv_name}")
dictionary_path <- file.path(base_dir, "{dictionary_name}")

# Several answers in one cell, as codes joined by ";": kept as text, because a
# factor holds one value per respondent.
multiple <- c({listed})

survey_data <- read.csv(
  data_path,
  stringsAsFactors = FALSE,
  check.names = FALSE,
  na.strings = "",
  fileEncoding = "UTF-8"
)
survey_dictionary <- jsonlite::fromJSON(dictionary_path, simplifyVector = FALSE)

for (name in names(survey_dictionary)) {{
  variable <- survey_dictionary[[name]]
  if (!name %in% names(survey_data)) {{
    next
  }}

  if (!name %in% multiple) {{
    missing_codes <- c()
    if (!is.null(variable$missing) && length(variable$missing) > 0) {{
      missing_codes <- type.convert(
        unlist(lapply(variable$missing, function(item) item$code), use.names = FALSE),
        as.is = TRUE
      )
      survey_data[[name]][survey_data[[name]] %in% missing_codes] <- NA
    }}

    if (!is.null(variable$labels) && length(variable$labels) > 0) {{
      levels <- type.convert(names(variable$labels), as.is = TRUE)
      labels <- unname(unlist(variable$labels, use.names = FALSE))
      keep <- !(levels %in% missing_codes)
      levels <- levels[keep]
      labels <- labels[keep]
      # A code the codebook has no label for stays, under its own code, rather
      # than turning into NA without a word.
      values <- survey_data[[name]]
      unlabeled <- sort(setdiff(unique(values[!is.na(values)]), levels))
      survey_data[[name]] <- factor(
        values,
        levels = c(levels, unlabeled),
        labels = c(labels, as.character(unlabeled))
      )
    }}
  }}

  if (!is.null(variable$label)) {{
    attr(survey_data[[name]], "label") <- variable$label
  }}
}}

survey_data
"""
